all: day01.out day02.out day03.out day04.out day05.out

clean:
	rm *.out

day01.out: day01.cpp
	g++ -o day01.out day01.cpp

day02.out: day02.cpp
	g++ -o day02.out day02.cpp

day03.out: day03.cpp
	g++ -o day03.out day03.cpp

day04.out: day04.cpp
	g++ -o day04.out day04.cpp

day05.out: day05.cpp
	g++ -o day05.out day05.cpp

