all: day01 day02 day03 day04 day05

day01: day01.cpp
	g++ -o day01 day01.cpp

day02: day02.cpp
	g++ -o day02 day02.cpp

day03: day03.cpp
	g++ -o day03 day03.cpp

day04: day04.cpp
	g++ -o day04 day04.cpp


day05: day05.cpp
	g++ -o day05 day05.cpp

