all: day01 day02 day03 day04 day05

clean:
	rm *.out

day01: day01.cpp
	g++ -o day01.out day01.cpp

day02: day02.cpp
	g++ -o day02.out day02.cpp

day03: day03.cpp
	g++ -o day03.out day03.cpp

day04: day04.cpp
	g++ -o day04.out day04.cpp

day05: day05.cpp
	g++ -o day05.out day05.cpp

